### ISSUE TITLE
Docker Setup screen doesnt fit browser window

### ISSUE THREAD

**Issue by truthsword** [Forceu/Gokapi#205] opened 2024-09-01 21:37 UTC
![](https://i.imgur.com/GF792ow.png)
There is no option to scroll up, and reducing browser magnification does not reveal the full setup window. 

Later, nearing setup completion there is this:
![](https://i.imgur.com/g0xOIno.png)

However there is no apparent console entry, so one can only enter "Continue".

**Comment by Forceu** [comment] 2024-09-04 10:23
Hi, thanks for the feedback! What is your display resolution?

The password has to be entered in the console of the application / container. Are you using Docker?

**Comment by truthsword** [comment] 2024-09-05 14:13
2880x1620

**Comment by Forceu** [comment] 2024-12-05 19:12
Unfortunately I am unable to reproduce the problem, even when trying multiple resolutions. I will close this for now, as the setup can still be completed. If anyone else has the same problem, please report here

**Closed by Forceu** 2024-12-05 19:12 UTC
