### ISSUE TITLE
Enhancement Request: Create "drop zone" for files to be sent to the admin

### ISSUE THREAD

**Issue by acourter27** [Forceu/Gokapi#36] opened 2021-12-30 22:49 UTC
It'd be cool to be able to create a temporary "upload zone" or "drop zone" link that you could send to someone and have them upload a file. Ideally you'd still be able to set the criteria up front (days, downloads, password) so that the user couldn't change them.

That way, you could send a link to someone, have them drop a file, but you're the only one who knows the password so only you can receive the file. That would still keep the system secure and not open, but would allow a quick way for someone to send you a file.

**Comment by Forceu** [comment] 2021-12-30 23:06
Thanks for the suggestion! It is pretty much a duplicate of #25, where I was thinking of having an additional menu for file requests. I am currently working on a setup GUI with additional authentication providers which is almost finished. Thereafter I will implement encryption and then work on the request feature.

**Closed by Forceu** 2021-12-30 23:06 UTC
